# Custom Language File for Launcher Customizer

[ejs.app]
title = "Cobblemon Ultima Launcher"

[ejs.landing]
mediaGitHubURL = "https://cobblemon-ultima.fr"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/hUF3hgxbMx"

[ejs.settings]
sourceGithubLink = "https://github.com/acoudray/CobblemonUltimaLauncher"
supportLink = "https://github.com/acoudray/CobblemonUltimaLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR COBBLEMON ULTIMA"
welcomeDescription = "⭐ Rejoignez l'aventure Cobblemon ultime ⭐ Un serveur Cobblemon Français réunissant des développeurs compétents et a l'écoute de leur communauté avec des mods faits mains, un parc Safari, une capitale unique, des spawn de pokémons légendaires naturels, des boss, des événements ! Et plus encore 👀. Nous vous attendons avec impatience ! 🔥"
welcomeDescCTA = "Rejoins nous !"
